// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthenticationScopes bearerAuthenticationContextKey = "BearerAuthentication.Scopes"
)

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password *string `json:"password,omitempty"`
	Username *string `json:"username,omitempty"`
}

// Pessoa defines model for Pessoa.
type Pessoa struct {
	// Id Código da pessoa
	Id *int64 `json:"id,omitempty"`

	// Nome Nome da pessoa
	Nome string `json:"nome"`
}

// bearerAuthenticationContextKey is the context key for BearerAuthentication security scheme
type bearerAuthenticationContextKey string

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// CreateJSONRequestBody defines body for Create for application/json ContentType.
type CreateJSONRequestBody = Pessoa

// UpdateJSONRequestBody defines body for Update for application/json ContentType.
type UpdateJSONRequestBody = Pessoa

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /login)
	Login(ctx echo.Context) error
	// Retorna uma lista de pessoas
	// (GET /pessoa)
	GetAll(ctx echo.Context) error
	// Cadastra uma pessoa
	// (POST /pessoa)
	Create(ctx echo.Context) error
	// Deleta uma pessoa
	// (DELETE /pessoa/{id})
	Delete(ctx echo.Context, id int64) error
	// Retorna uma pessoa
	// (GET /pessoa/{id})
	GetById(ctx echo.Context, id int64) error
	// Atualiza uma pessoa
	// (PUT /pessoa/{id})
	Update(ctx echo.Context, id int64) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Login(ctx)
	return err
}

// GetAll converts echo context to params.
func (w *ServerInterfaceWrapper) GetAll(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthenticationScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAll(ctx)
	return err
}

// Create converts echo context to params.
func (w *ServerInterfaceWrapper) Create(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthenticationScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Create(ctx)
	return err
}

// Delete converts echo context to params.
func (w *ServerInterfaceWrapper) Delete(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(BearerAuthenticationScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Delete(ctx, id)
	return err
}

// GetById converts echo context to params.
func (w *ServerInterfaceWrapper) GetById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(BearerAuthenticationScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetById(ctx, id)
	return err
}

// Update converts echo context to params.
func (w *ServerInterfaceWrapper) Update(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(BearerAuthenticationScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Update(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(options.BaseURL+"/login", wrapper.Login, options.OperationMiddlewares["login"]...)
	router.GET(options.BaseURL+"/pessoa", wrapper.GetAll, options.OperationMiddlewares["getAll"]...)
	router.POST(options.BaseURL+"/pessoa", wrapper.Create, options.OperationMiddlewares["create"]...)
	router.DELETE(options.BaseURL+"/pessoa/:id", wrapper.Delete, options.OperationMiddlewares["delete"]...)
	router.GET(options.BaseURL+"/pessoa/:id", wrapper.GetById, options.OperationMiddlewares["getById"]...)
	router.PUT(options.BaseURL+"/pessoa/:id", wrapper.Update, options.OperationMiddlewares["update"]...)

}
